### ISSUE TITLE
在m4n板卡上，AX650芯片，利用opencv读图片一个图片耗时100ms则个可以优化吗？

### ISSUE THREAD

**Issue by skming666** [AXERA-TECH/ax-samples#115]
1：利用opencv在板子上读图片发现耗时太长？有没有解决办法？
2：如果在板子上读MP4视频？利用ax_sample的例子然后交叉编译后，放在板子上显示视频打不开？这个是因为ax-samples中的opencv库不全吗？怎么解决
3：如果在板子上读取usb摄像头，怎么处理？有demo吗
感谢，感谢！

**Comment by ZHEQIUSHUI** [comment]
1、软解码肯定慢
2、视频输入的sample用 ax-pipeline，附带的opencv只有基础的imgproc模块，你可以自己编译完整的opencv进行视频和USB相机的读取
3、同2
