### ISSUE TITLE
Failed to run ax_yolov5s

### ISSUE THREAD

**Issue by sagar1899** [AXERA-TECH/ax-samples#133]
Hi,
I have build AX650A and running ax_yolov5s using below command.

./ax_yolov5s -m yolov5s.axmodel -i cat.jpg on CPU. and i got below error.

--------------------------------------
model file : /home/sagarkhimani/Downloads/AXERA/650/yolov5s.joint
image file : cat.jpg
img_h, img_w : 640 640
--------------------------------------
**Failed to open /proc/ax_proc/logctl**

is AX650 board is mandatory to run ax_yolov5s executable ?

**Comment by BUG1989** [comment]
You can find the right version of ax_yolov5s on GoogleDrive or build it follow the https://github.com/AXERA-TECH/ax-samples/blob/main/docs/compile_650.md
