### ISSUE TITLE
where did the ax-pipeline repository gone?

### ISSUE THREAD

**Issue by MikeTuev** [AXERA-TECH/ax-samples#147]
where did the ax-pipeline repository gone?

**Comment by BUG1989** [comment]
The project is closed.If you need, please leave your email, I will send you the last version of the compressed package.

**Comment by MikeTuev** [comment]
Please ra9ftm@gmail.com

**Comment by MikeTuev** [comment]
@BUG1989 Unfortunately, I haven't received it.
