### ISSUE TITLE
ax_engine_api.h这个文件是不是没有提供啊

### ISSUE THREAD

**Issue by Ko24Bewjw** [AXERA-TECH/ax-samples#150]
[  1%] Building CXX object examples/ax650/CMakeFiles/ax_model_info.dir/ax_model_info.cc.o
In file included from /home/wzhpc/wjw/github_file/AXERA_DEMO/ax-samples/examples/ax650/ax_model_info.cc:27:0:
/home/wzhpc/wjw/github_file/AXERA_DEMO/ax-samples/examples/ax650/middleware/io.hpp:29:10: fatal error: ax_engine_api.h: No such file or directory
 #include <ax_engine_api.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [examples/ax650/CMakeFiles/ax_model_info.dir/build.make:63: examples/ax650/CMakeFiles/ax_model_info.dir/ax_model_info.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: examples/ax650/CMakeFiles/ax_model_info.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by BUG1989** [comment]
举个例子，交叉编译时需要显式的指定 bsp 中的 lib 和 include 文件夹，你可以参考 https://github.com/AXERA-TECH/ax-samples/blob/main/.github/workflows/build_650.yml 中的流程
