### ISSUE TITLE
yolov6s在AX650N推理耗时与benchmarks提供的耗时不符

### ISSUE THREAD

**Issue by 455670288** [AXERA-TECH/ax-samples#151]
将官方的yolov6s.onnx转换成axmodel后，在AX650N上使用ax_run_model测试平均耗时为13ms。请问你们是否有对v6的检测头做过优化?  现在导出的检测头尺寸为(1,8400,85)。 这个输出能否与你们的yolov6后处理对应？

**Comment by 455670288** [comment]
![xx](https://github.com/user-attachments/assets/e3c0c57e-2135-4060-993b-66a1763ae2f6)
ax-samples中执行ax_yolov6. 输出数据错误。

**Comment by BUG1989** [comment]
输出头有裁剪操作，请参考 YOLOv8s 的 onnx 裁剪流程 https://zhuanlan.zhihu.com/p/683050593
