### ISSUE TITLE
有芯片规格书以及开发板之类？

### ISSUE THREAD

**Issue by bing20138163** [AXERA-TECH/ax-samples#3]
有芯片规格书以及开发板资料？

**Comment by BUG1989** [comment]
1. 当前阶段如果有商务评估需求，可以联系 AXERA 的商务获取相关资料；
2. 面向社区开发者的板子和资料，将在 7月初 更新。

**Comment by BUG1989** [comment]
@bing20138163 QQ技术交流群已经上传 brief PDF
