### ISSUE TITLE
a question about yolov5-seg pr

### ISSUE THREAD

**Issue by FeiGeChuanShu** [AXERA-TECH/ax-samples#48]
木有支持roialign，所以后处理太慢了，能否忍受这个pr？
Post time:43.10 ms

![yolov5s_out](https://user-images.githubusercontent.com/80833738/202078906-f3a23711-b0cd-494a-8d4c-946d9e59cde8.jpg)

**Comment by BUG1989** [comment]
先解决有无问题，优化是长久的持续性工作，感谢 @FeiGeChuanShu 实现 yolov5-seg
