### ISSUE TITLE
Facial Recognition with Arcface

### ISSUE THREAD

**Issue by ltdat1201** [AXERA-TECH/ax-samples#58]
Hello, I'm very interested in your project, I'm also working on implementing facial recognition on some camera chipsets.  So, do you have plans to support facial recognition on your chipset? Could you support example to run arcface on AX620A?

**Comment by ZHEQIUSHUI** [comment]
now face detection model is get ready 👍 
[ax_scrfd_steps.cc](https://github.com/AXERA-TECH/ax-samples/blob/main/examples/ax_scrfd_steps.cc)
[ax_yolov7s_face_steps.cc](https://github.com/AXERA-TECH/ax-samples/blob/main/examples/ax_yolov7s_face_steps.cc)
[ax_yolov5s_face_steps.cc](https://github.com/AXERA-TECH/ax-samples/blob/main/examples/ax_yolov5s_face_steps.cc)

and the arcface model is similar to classification,you can reference the code just like  [ax_classification_steps.cc](https://github.com/AXERA-TECH/ax-samples/blob/main/examples/ax_classification_steps.cc) to get the face feature

**Comment by ltdat1201** [comment]
Hello @ZHEQIUSHUI ,
Thanks for your support, I am trying to convert the origin onnx arcface models (https://github.com/onnx/models/tree/main/vision/body_analysis/arcface) by Pulsar tool but still not successful yet. Could you help me with the instruction to convert this model to .joint format? My target hardware is AX620A. Thank you so much.

**Comment by ZHEQIUSHUI** [comment]
you can read the pulsar web docs in [here](https://pulsar-docs.readthedocs.io/en/latest/)

**Comment by ltdat1201** [comment]
Hello @ZHEQIUSHUI , we are following the pulsar document and trying to convert the arcface model. However, we occur this error so could you help me? 
p/s: we are just newbies in this field.
The error picture:
![image_2022_12_15T09_18_41_441Z](https://user-images.githubusercontent.com/31626239/208039740-d796526b-4312-489c-b3d9-ade22c17eaf5.png)
this is our configure file: 
[test.prototxt.txt](https://github.com/AXERA-TECH/ax-samples/files/10243294/test.prototxt.txt)

**Comment by shitouren1994** [comment]
1. you need use onnxsimplfy to simple this model
2. after simplfy ,if bn layer has a attribute called "spatial"; you need delete it
3. dropout layer should be deleted

the fixed model is tool big, i cannot upload here.

**Comment by ltdat1201** [comment]
Hello @shitouren1994 , 
I will try following your suggestion. If you can, please give me the fixed model and more email information: ltdat1201@gmail.com
Thanks for your support.
