### ISSUE TITLE
Metrics for `.joint` models

### ISSUE THREAD

**Issue by mikel-brostrom** [AXERA-TECH/ax-samples#76]
Could you provide metrics for the available exported models, or at least a subset of them, so that we can understand what performance degradation is to be expected when INT8-quantinzing models with `pulsar`?

**Comment by mikel-brostrom** [comment]
Moreover, no detailed information is available for the architecture topology of the exported models. How well does `pulsar` handle Swish, GELU activations when exporting and specially INT8 quantization?

**Comment by mikel-brostrom** [comment]
https://github.com/AXERA-TECH/ax-samples/issues/73

**Comment by kalcohol** [comment]
Hi [mikel-brostrom](https://github.com/mikel-brostrom),
u can get `pulsar` from [ax-pi wiki](https://wiki.sipeed.com/hardware/zh/maixIII/ax-pi/axpi.html)
so compile your models and then have a better know of each performance & metrics of your models on ax620 chips.
the released models are not aiming to show the performance & metrics, the samples are provided to showing that how to use the npu api.

so #73 that demo models cannot provide performance degradation of dataset as your wish.
(we do not suggest customers using the models in final produt directly, so the models are not set as its best precision)
