### ISSUE TITLE
yolov5s 6.2 训练自己的模型 best.onnx 转换 .joint 在板子上推理输出结果不对

### ISSUE THREAD

**Issue by llf10811020205** [AXERA-TECH/ax-samples#88]
1、排除best.onnx 问题
2、AX620A 板子上可跑推理结果
3、推理结果出现大量的dense bbox  且都是错误的框

**Comment by llf10811020205** [comment]
本地测试best.onnx 推理结果正确

**Comment by llf10811020205** [comment]
![image](https://github.com/AXERA-TECH/ax-samples/assets/4935062/950f629e-1c7f-4cbe-a002-0914baecd21e)

**Comment by BUG1989** [comment]
麻烦提供下 config 文件
